name: 混淆当前版本源码

on:
  workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # 建议使用更新的版本

      - name: Install Obfuscator
        run: npm install -g javascript-obfuscator

      - name: Prepare file
        run: |
          if [ ! -f _worker.js ]; then
            echo "Error: _worker.js not found!"
            exit 1
          fi
          cp _worker.js _worker_temp.js

      - name: Run Obfuscation
        run: |
          javascript-obfuscator _worker_temp.js --output _worker.js \
          --compact true \
          --control-flow-flattening true \
          --control-flow-flattening-threshold 1 \
          --dead-code-injection true \
          --dead-code-injection-threshold 1 \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'rc4' \
          --string-array-threshold 1 \
          --transform-object-keys true \
          --unicode-escape-sequence true

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _worker.js
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: obfuscate _worker.js"
            git push origin HEAD:${{ github.ref }}
          fi
